//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDDModder.BrickEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDDModder.BrickEditor.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory.
        /// </summary>
        internal static string BuildConfig_Browse {
            get {
                return ResourceManager.GetString("BuildConfig_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDD folder.
        /// </summary>
        internal static string BuildConfig_LDD {
            get {
                return ResourceManager.GetString("BuildConfig_LDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage configurations....
        /// </summary>
        internal static string BuildConfig_Manage {
            get {
                return ResourceManager.GetString("BuildConfig_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Caption_Confirmation {
            get {
                return ResourceManager.GetString("Caption_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        internal static string Caption_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Caption_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDD part files generation.
        /// </summary>
        internal static string Caption_LddPartGeneration {
            get {
                return ResourceManager.GetString("Caption_LddPartGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file.
        /// </summary>
        internal static string Caption_OpeningFile {
            get {
                return ResourceManager.GetString("Caption_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening project.
        /// </summary>
        internal static string Caption_OpeningProject {
            get {
                return ResourceManager.GetString("Caption_OpeningProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover last session.
        /// </summary>
        internal static string Caption_RecoverLastProject {
            get {
                return ResourceManager.GetString("Caption_RecoverLastProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string Caption_SaveBeforeClose {
            get {
                return ResourceManager.GetString("Caption_SaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Window Layout.
        /// </summary>
        internal static string Caption_SaveWindowLayout {
            get {
                return ResourceManager.GetString("Caption_SaveWindowLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup validations.
        /// </summary>
        internal static string Caption_StartupValidations {
            get {
                return ResourceManager.GetString("Caption_StartupValidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string Caption_UnexpectedError {
            get {
                return ResourceManager.GetString("Caption_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Caption_Warning {
            get {
                return ResourceManager.GetString("Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the project..
        /// </summary>
        internal static string Error_CreatingProject {
            get {
                return ResourceManager.GetString("Error_CreatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening a file..
        /// </summary>
        internal static string Error_OpeningFile {
            get {
                return ResourceManager.GetString("Error_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening the project..
        /// </summary>
        internal static string Error_OpeningProject {
            get {
                return ResourceManager.GetString("Error_OpeningProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured LDD environment is not valid but LDD appears to be correctly installed..
        /// </summary>
        internal static string LddConfigInvalid {
            get {
                return ResourceManager.GetString("LddConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDD installation was not found.
        ///Some features will not work properly..
        /// </summary>
        internal static string LddInstallNotFound {
            get {
                return ResourceManager.GetString("LddInstallNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection &quot;{0}&quot; is used by bones.
        ///Do you want to delete anyway?.
        /// </summary>
        internal static string Message_ConfirmDeleteBoneConnection {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteBoneConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element &quot;{0}&quot; is referenced by other elements of the project.
        ///Do you want to delete anyway?.
        /// </summary>
        internal static string Message_ConfirmDeleteReferencedElement {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteReferencedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection &quot;{0}&quot; is referenced by elements of the model.
        ///Do you want to delete anyway?.
        /// </summary>
        internal static string Message_ConfirmDeleteStudConnection {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteStudConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files for this part already exists.
        ///Are-you sure you want to overwrite  them?
        ///
        ///*You can remove this confirmation in the settings..
        /// </summary>
        internal static string Message_ConfirmOverwritePartFiles {
            get {
                return ResourceManager.GetString("Message_ConfirmOverwritePartFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some model components references studs that are outside the new size.
        ///Do you want to proceed anyway?.
        /// </summary>
        internal static string Message_ConfirmResizeStuds {
            get {
                return ResourceManager.GetString("Message_ConfirmResizeStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library &apos;freetype6.dll&quot; could not be loaded.
        ///This library is used to draw text in OpenGL.
        ///The application can still work but no text will be displayed in the viewport..
        /// </summary>
        internal static string Message_CouldNotLoadFreetype6 {
            get {
                return ResourceManager.GetString("Message_CouldNotLoadFreetype6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not generate LDD part files.
        ///Check validation panel for more details..
        /// </summary>
        internal static string Message_FileGenerationError {
            get {
                return ResourceManager.GetString("Message_FileGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Resources.
        /// </summary>
        internal static string Message_InitializingResources {
            get {
                return ResourceManager.GetString("Message_InitializingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing User Interface.
        /// </summary>
        internal static string Message_InitializingUI {
            get {
                return ResourceManager.GetString("Message_InitializingUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout name already exist..
        /// </summary>
        internal static string Message_LayoutNameAlreadyExist {
            get {
                return ResourceManager.GetString("Message_LayoutNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files generated successfully..
        /// </summary>
        internal static string Message_LddFilesGenerated {
            get {
                return ResourceManager.GetString("Message_LddFilesGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app did not close correctly, do you want to recover the project?.
        /// </summary>
        internal static string Message_RecoverProject {
            get {
                return ResourceManager.GetString("Message_RecoverProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes made?.
        /// </summary>
        internal static string Message_SaveChanges {
            get {
                return ResourceManager.GetString("Message_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the project?.
        /// </summary>
        internal static string Message_SaveNewProject {
            get {
                return ResourceManager.GetString("Message_SaveNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Name:.
        /// </summary>
        internal static string Message_SaveWindowLayout {
            get {
                return ResourceManager.GetString("Message_SaveWindowLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        ///For more details, check the log file..
        /// </summary>
        internal static string Message_UnhandledException {
            get {
                return ResourceManager.GetString("Message_UnhandledException", resourceCulture);
            }
        }
    }
}
