//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDDModder.BrickEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDDModder.BrickEditor.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select directory.
        /// </summary>
        internal static string BuildConfig_Browse {
            get {
                return ResourceManager.GetString("BuildConfig_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LDD folder.
        /// </summary>
        internal static string BuildConfig_LDD {
            get {
                return ResourceManager.GetString("BuildConfig_LDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage configurations....
        /// </summary>
        internal static string BuildConfig_Manage {
            get {
                return ResourceManager.GetString("BuildConfig_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string Caption_Confirmation {
            get {
                return ResourceManager.GetString("Caption_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete confirmation.
        /// </summary>
        internal static string Caption_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Caption_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LDD part files generation.
        /// </summary>
        internal static string Caption_LddPartGeneration {
            get {
                return ResourceManager.GetString("Caption_LddPartGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opening file.
        /// </summary>
        internal static string Caption_OpeningFile {
            get {
                return ResourceManager.GetString("Caption_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opening project.
        /// </summary>
        internal static string Caption_OpeningProject {
            get {
                return ResourceManager.GetString("Caption_OpeningProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save project.
        /// </summary>
        internal static string Caption_SaveBeforeClose {
            get {
                return ResourceManager.GetString("Caption_SaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Startup validations.
        /// </summary>
        internal static string Caption_StartupValidations {
            get {
                return ResourceManager.GetString("Caption_StartupValidations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while creating the project..
        /// </summary>
        internal static string Error_CreatingProject {
            get {
                return ResourceManager.GetString("Error_CreatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while opening a file..
        /// </summary>
        internal static string Error_OpeningFile {
            get {
                return ResourceManager.GetString("Error_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while opening the project..
        /// </summary>
        internal static string Error_OpeningProject {
            get {
                return ResourceManager.GetString("Error_OpeningProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The configured LDD environment is not valid but LDD appears to be correctly installed..
        /// </summary>
        internal static string LddConfigInvalid {
            get {
                return ResourceManager.GetString("LddConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LDD installation was not found.
        ///Some features will not work properly..
        /// </summary>
        internal static string LddInstallNotFound {
            get {
                return ResourceManager.GetString("LddInstallNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The connection &quot;{0}&quot; is used by bones.
        ///Do you want to delete anyway?.
        /// </summary>
        internal static string Message_ConfirmDeleteBoneConnection {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteBoneConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The connection &quot;{0}&quot; is referenced by elements of the model.
        ///Do you want to delete anyway?.
        /// </summary>
        internal static string Message_ConfirmDeleteStudConnection {
            get {
                return ResourceManager.GetString("Message_ConfirmDeleteStudConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some model components references studs that are outside the new size.
        ///Do you want to proceed anyway?.
        /// </summary>
        internal static string Message_ConfirmResizeStuds {
            get {
                return ResourceManager.GetString("Message_ConfirmResizeStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not generate LDD part files.
        ///Check validation panel for more details..
        /// </summary>
        internal static string Message_FileGenerationError {
            get {
                return ResourceManager.GetString("Message_FileGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TODO.
        /// </summary>
        internal static string Message_RecoverProject {
            get {
                return ResourceManager.GetString("Message_RecoverProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save the changes made?.
        /// </summary>
        internal static string Message_SaveChanges {
            get {
                return ResourceManager.GetString("Message_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save the project?.
        /// </summary>
        internal static string Message_SaveNewProject {
            get {
                return ResourceManager.GetString("Message_SaveNewProject", resourceCulture);
            }
        }
    }
}
