//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDDModder.BrickEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDDModder.BrickEditor.Resources.ModelLocalizations", typeof(ModelLocalizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string CollisionType_Box {
            get {
                return ResourceManager.GetString("CollisionType_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere.
        /// </summary>
        internal static string CollisionType_Sphere {
            get {
                return ResourceManager.GetString("CollisionType_Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical (bars &amp; technic).
        /// </summary>
        internal static string ConnectorType_Axel {
            get {
                return ResourceManager.GetString("ConnectorType_Axel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball joint &amp; misc.
        /// </summary>
        internal static string ConnectorType_Ball {
            get {
                return ResourceManager.GetString("ConnectorType_Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studs (bricks).
        /// </summary>
        internal static string ConnectorType_Custom2DField {
            get {
                return ResourceManager.GetString("ConnectorType_Custom2DField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed coupling (tires, doors, etc.).
        /// </summary>
        internal static string ConnectorType_Fixed {
            get {
                return ResourceManager.GetString("ConnectorType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        internal static string ConnectorType_Gear {
            get {
                return ResourceManager.GetString("ConnectorType_Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinge.
        /// </summary>
        internal static string ConnectorType_Hinge {
            get {
                return ResourceManager.GetString("ConnectorType_Hinge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train rails.
        /// </summary>
        internal static string ConnectorType_Rail {
            get {
                return ResourceManager.GetString("ConnectorType_Rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string ConnectorType_Slider {
            get {
                return ResourceManager.GetString("ConnectorType_Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate model.
        /// </summary>
        internal static string Label_AlternateMeshes {
            get {
                return ResourceManager.GetString("Label_AlternateMeshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical conn..
        /// </summary>
        internal static string Label_AxelConnectors {
            get {
                return ResourceManager.GetString("Label_AxelConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balls.
        /// </summary>
        internal static string Label_BallConnectors {
            get {
                return ResourceManager.GetString("Label_BallConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick.
        /// </summary>
        internal static string Label_Brick {
            get {
                return ResourceManager.GetString("Label_Brick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick tubes.
        /// </summary>
        internal static string Label_BrickTubeComponents {
            get {
                return ResourceManager.GetString("Label_BrickTubeComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tubes.
        /// </summary>
        internal static string Label_BrickTubes {
            get {
                return ResourceManager.GetString("Label_BrickTubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        internal static string Label_CollisionBoxes {
            get {
                return ResourceManager.GetString("Label_CollisionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collisions.
        /// </summary>
        internal static string Label_Collisions {
            get {
                return ResourceManager.GetString("Label_Collisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spheres.
        /// </summary>
        internal static string Label_CollisionSpheres {
            get {
                return ResourceManager.GetString("Label_CollisionSpheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string Label_Component {
            get {
                return ResourceManager.GetString("Label_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string Label_Connections {
            get {
                return ResourceManager.GetString("Label_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studs.
        /// </summary>
        internal static string Label_Custom2DFieldConnectors {
            get {
                return ResourceManager.GetString("Label_Custom2DFieldConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration.
        /// </summary>
        internal static string Label_Decoration {
            get {
                return ResourceManager.GetString("Label_Decoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration surface.
        /// </summary>
        internal static string Label_DecorationSurface {
            get {
                return ResourceManager.GetString("Label_DecorationSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration surface {0}.
        /// </summary>
        internal static string Label_DecorationSurfaceNumber {
            get {
                return ResourceManager.GetString("Label_DecorationSurfaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal model.
        /// </summary>
        internal static string Label_DefaultMeshes {
            get {
                return ResourceManager.GetString("Label_DefaultMeshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female stud.
        /// </summary>
        internal static string Label_FemaleStud {
            get {
                return ResourceManager.GetString("Label_FemaleStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female studs.
        /// </summary>
        internal static string Label_FemaleStudComponents {
            get {
                return ResourceManager.GetString("Label_FemaleStudComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studs (female).
        /// </summary>
        internal static string Label_FemaleStuds {
            get {
                return ResourceManager.GetString("Label_FemaleStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed conn..
        /// </summary>
        internal static string Label_FixedConnectors {
            get {
                return ResourceManager.GetString("Label_FixedConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        internal static string Label_GearConnectors {
            get {
                return ResourceManager.GetString("Label_GearConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        internal static string Label_Geometry {
            get {
                return ResourceManager.GetString("Label_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinges.
        /// </summary>
        internal static string Label_HingeConnectors {
            get {
                return ResourceManager.GetString("Label_HingeConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main surface.
        /// </summary>
        internal static string Label_MainSurface {
            get {
                return ResourceManager.GetString("Label_MainSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male studs.
        /// </summary>
        internal static string Label_MaleStudComponents {
            get {
                return ResourceManager.GetString("Label_MaleStudComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studs (male).
        /// </summary>
        internal static string Label_MaleStuds {
            get {
                return ResourceManager.GetString("Label_MaleStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh.
        /// </summary>
        internal static string Label_Mesh {
            get {
                return ResourceManager.GetString("Label_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string Label_Models {
            get {
                return ResourceManager.GetString("Label_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New part.
        /// </summary>
        internal static string Label_NewPartProject {
            get {
                return ResourceManager.GetString("Label_NewPartProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active project.
        /// </summary>
        internal static string Label_NoActiveProject {
            get {
                return ResourceManager.GetString("Label_NoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string Label_Part {
            get {
                return ResourceManager.GetString("Label_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part models.
        /// </summary>
        internal static string Label_PartComponents {
            get {
                return ResourceManager.GetString("Label_PartComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part %partid%.
        /// </summary>
        internal static string Label_PartProjectName {
            get {
                return ResourceManager.GetString("Label_PartProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Label_Project {
            get {
                return ResourceManager.GetString("Label_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rails.
        /// </summary>
        internal static string Label_RailConnectors {
            get {
                return ResourceManager.GetString("Label_RailConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        internal static string Label_SliderConnectors {
            get {
                return ResourceManager.GetString("Label_SliderConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stud.
        /// </summary>
        internal static string Label_Stud {
            get {
                return ResourceManager.GetString("Label_Stud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studs.
        /// </summary>
        internal static string Label_Studs {
            get {
                return ResourceManager.GetString("Label_Studs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        internal static string Label_Surface {
            get {
                return ResourceManager.GetString("Label_Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfaces.
        /// </summary>
        internal static string Label_Surfaces {
            get {
                return ResourceManager.GetString("Label_Surfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model does not reference any stud..
        /// </summary>
        internal static string MODEL_STUDS_NOT_DEFINED {
            get {
                return ResourceManager.GetString("MODEL_STUDS_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model does not reference any stud. Therefore the alternate model will never be displayed..
        /// </summary>
        internal static string MODEL_STUDS_NOT_DEFINED_ALT {
            get {
                return ResourceManager.GetString("MODEL_STUDS_NOT_DEFINED_ALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick tube.
        /// </summary>
        internal static string ModelComponentType_BrickTube {
            get {
                return ResourceManager.GetString("ModelComponentType_BrickTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stud (female).
        /// </summary>
        internal static string ModelComponentType_FemaleStud {
            get {
                return ResourceManager.GetString("ModelComponentType_FemaleStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stud (male).
        /// </summary>
        internal static string ModelComponentType_MaleStud {
            get {
                return ResourceManager.GetString("ModelComponentType_MaleStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part model.
        /// </summary>
        internal static string ModelComponentType_Part {
            get {
                return ResourceManager.GetString("ModelComponentType_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string NodeRangeFormat1 {
            get {
                return ResourceManager.GetString("NodeRangeFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}+.
        /// </summary>
        internal static string NodeRangeFormat2 {
            get {
                return ResourceManager.GetString("NodeRangeFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part description is empty..
        /// </summary>
        internal static string PART_EMPTY_DESCRIPTION {
            get {
                return ResourceManager.GetString("PART_EMPTY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a part ID..
        /// </summary>
        internal static string PART_EMPTY_PART_ID {
            get {
                return ResourceManager.GetString("PART_EMPTY_PART_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part bounding box is not defined..
        /// </summary>
        internal static string PART_NO_BOUNDING {
            get {
                return ResourceManager.GetString("PART_NO_BOUNDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geometry bounding box is not defined..
        /// </summary>
        internal static string PART_NO_GEOMETRYBOUNDING {
            get {
                return ResourceManager.GetString("PART_NO_GEOMETRYBOUNDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no bone defined. The part cannot be flexible..
        /// </summary>
        internal static string PROJECT_NO_BONES {
            get {
                return ResourceManager.GetString("PROJECT_NO_BONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no collision defined..
        /// </summary>
        internal static string PROJECT_NO_COLLISIONS {
            get {
                return ResourceManager.GetString("PROJECT_NO_COLLISIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection defined. The part will not connect with anything..
        /// </summary>
        internal static string PROJECT_NO_CONNECTIONS {
            get {
                return ResourceManager.GetString("PROJECT_NO_CONNECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration problem found..
        /// </summary>
        internal static string PROJECT_NO_ISSUES {
            get {
                return ResourceManager.GetString("PROJECT_NO_ISSUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part must have at least one surface..
        /// </summary>
        internal static string PROJECT_NO_SURFACES {
            get {
                return ResourceManager.GetString("PROJECT_NO_SURFACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced stud is invalid..
        /// </summary>
        internal static string STUD_CONNECTION_FIELD_INVALID {
            get {
                return ResourceManager.GetString("STUD_CONNECTION_FIELD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced stud is not defined..
        /// </summary>
        internal static string STUD_CONNECTION_FIELD_NOT_DEFINED {
            get {
                return ResourceManager.GetString("STUD_CONNECTION_FIELD_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is not set or invalid..
        /// </summary>
        internal static string STUD_CONNECTION_NOT_DEFINED {
            get {
                return ResourceManager.GetString("STUD_CONNECTION_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surface {0} does not contain any model..
        /// </summary>
        internal static string SURFACE_NO_MODELS {
            get {
                return ResourceManager.GetString("SURFACE_NO_MODELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surface {0} has some models without texture coordinates..
        /// </summary>
        internal static string SURFACE_NO_TEXTURED_MODEL {
            get {
                return ResourceManager.GetString("SURFACE_NO_TEXTURED_MODEL", resourceCulture);
            }
        }
    }
}
