//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDDModder.BrickEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelLocalizations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDDModder.BrickEditor.Resources.ModelLocalizations", typeof(ModelLocalizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Box.
        /// </summary>
        internal static string CollisionType_Box {
            get {
                return ResourceManager.GetString("CollisionType_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sphere.
        /// </summary>
        internal static string CollisionType_Sphere {
            get {
                return ResourceManager.GetString("CollisionType_Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cylindrical (bars &amp; technic).
        /// </summary>
        internal static string ConnectorType_Axel {
            get {
                return ResourceManager.GetString("ConnectorType_Axel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ball joint &amp; misc.
        /// </summary>
        internal static string ConnectorType_Ball {
            get {
                return ResourceManager.GetString("ConnectorType_Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs (bricks).
        /// </summary>
        internal static string ConnectorType_Custom2DField {
            get {
                return ResourceManager.GetString("ConnectorType_Custom2DField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed coupling (tires, doors, etc.).
        /// </summary>
        internal static string ConnectorType_Fixed {
            get {
                return ResourceManager.GetString("ConnectorType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gear.
        /// </summary>
        internal static string ConnectorType_Gear {
            get {
                return ResourceManager.GetString("ConnectorType_Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinge.
        /// </summary>
        internal static string ConnectorType_Hinge {
            get {
                return ResourceManager.GetString("ConnectorType_Hinge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Train rails.
        /// </summary>
        internal static string ConnectorType_Rail {
            get {
                return ResourceManager.GetString("ConnectorType_Rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slider.
        /// </summary>
        internal static string ConnectorType_Slider {
            get {
                return ResourceManager.GetString("ConnectorType_Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alternate model.
        /// </summary>
        internal static string Label_AlternateMeshes {
            get {
                return ResourceManager.GetString("Label_AlternateMeshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cylindrical conn..
        /// </summary>
        internal static string Label_AxelConnectors {
            get {
                return ResourceManager.GetString("Label_AxelConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balls.
        /// </summary>
        internal static string Label_BallConnectors {
            get {
                return ResourceManager.GetString("Label_BallConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bone.
        /// </summary>
        internal static string Label_Bone {
            get {
                return ResourceManager.GetString("Label_Bone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bones.
        /// </summary>
        internal static string Label_Bones {
            get {
                return ResourceManager.GetString("Label_Bones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brick.
        /// </summary>
        internal static string Label_Brick {
            get {
                return ResourceManager.GetString("Label_Brick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brick tubes.
        /// </summary>
        internal static string Label_BrickTubeComponents {
            get {
                return ResourceManager.GetString("Label_BrickTubeComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tubes.
        /// </summary>
        internal static string Label_BrickTubes {
            get {
                return ResourceManager.GetString("Label_BrickTubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collision.
        /// </summary>
        internal static string Label_Collision {
            get {
                return ResourceManager.GetString("Label_Collision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boxes.
        /// </summary>
        internal static string Label_CollisionBoxes {
            get {
                return ResourceManager.GetString("Label_CollisionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collisions.
        /// </summary>
        internal static string Label_Collisions {
            get {
                return ResourceManager.GetString("Label_Collisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spheres.
        /// </summary>
        internal static string Label_CollisionSpheres {
            get {
                return ResourceManager.GetString("Label_CollisionSpheres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Component.
        /// </summary>
        internal static string Label_Component {
            get {
                return ResourceManager.GetString("Label_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection.
        /// </summary>
        internal static string Label_Connection {
            get {
                return ResourceManager.GetString("Label_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connections.
        /// </summary>
        internal static string Label_Connections {
            get {
                return ResourceManager.GetString("Label_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs.
        /// </summary>
        internal static string Label_Custom2DFieldConnectors {
            get {
                return ResourceManager.GetString("Label_Custom2DFieldConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decoration.
        /// </summary>
        internal static string Label_Decoration {
            get {
                return ResourceManager.GetString("Label_Decoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decoration surface.
        /// </summary>
        internal static string Label_DecorationSurface {
            get {
                return ResourceManager.GetString("Label_DecorationSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decoration surface {0}.
        /// </summary>
        internal static string Label_DecorationSurfaceNumber {
            get {
                return ResourceManager.GetString("Label_DecorationSurfaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal model.
        /// </summary>
        internal static string Label_DefaultMeshes {
            get {
                return ResourceManager.GetString("Label_DefaultMeshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Female stud.
        /// </summary>
        internal static string Label_FemaleStud {
            get {
                return ResourceManager.GetString("Label_FemaleStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Female studs.
        /// </summary>
        internal static string Label_FemaleStudComponents {
            get {
                return ResourceManager.GetString("Label_FemaleStudComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs (female).
        /// </summary>
        internal static string Label_FemaleStuds {
            get {
                return ResourceManager.GetString("Label_FemaleStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed conn..
        /// </summary>
        internal static string Label_FixedConnectors {
            get {
                return ResourceManager.GetString("Label_FixedConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gears.
        /// </summary>
        internal static string Label_GearConnectors {
            get {
                return ResourceManager.GetString("Label_GearConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geometry.
        /// </summary>
        internal static string Label_Geometry {
            get {
                return ResourceManager.GetString("Label_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinges.
        /// </summary>
        internal static string Label_HingeConnectors {
            get {
                return ResourceManager.GetString("Label_HingeConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main surface.
        /// </summary>
        internal static string Label_MainSurface {
            get {
                return ResourceManager.GetString("Label_MainSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Male studs.
        /// </summary>
        internal static string Label_MaleStudComponents {
            get {
                return ResourceManager.GetString("Label_MaleStudComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs (male).
        /// </summary>
        internal static string Label_MaleStuds {
            get {
                return ResourceManager.GetString("Label_MaleStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mesh.
        /// </summary>
        internal static string Label_Mesh {
            get {
                return ResourceManager.GetString("Label_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model.
        /// </summary>
        internal static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Models.
        /// </summary>
        internal static string Label_Models {
            get {
                return ResourceManager.GetString("Label_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New part.
        /// </summary>
        internal static string Label_NewPartProject {
            get {
                return ResourceManager.GetString("Label_NewPartProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No active project.
        /// </summary>
        internal static string Label_NoActiveProject {
            get {
                return ResourceManager.GetString("Label_NoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part.
        /// </summary>
        internal static string Label_Part {
            get {
                return ResourceManager.GetString("Label_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part models.
        /// </summary>
        internal static string Label_PartComponents {
            get {
                return ResourceManager.GetString("Label_PartComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part %partid%.
        /// </summary>
        internal static string Label_PartProjectName {
            get {
                return ResourceManager.GetString("Label_PartProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        internal static string Label_Project {
            get {
                return ResourceManager.GetString("Label_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rails.
        /// </summary>
        internal static string Label_RailConnectors {
            get {
                return ResourceManager.GetString("Label_RailConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sliders.
        /// </summary>
        internal static string Label_SliderConnectors {
            get {
                return ResourceManager.GetString("Label_SliderConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stud.
        /// </summary>
        internal static string Label_Stud {
            get {
                return ResourceManager.GetString("Label_Stud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs.
        /// </summary>
        internal static string Label_Studs {
            get {
                return ResourceManager.GetString("Label_Studs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surface.
        /// </summary>
        internal static string Label_Surface {
            get {
                return ResourceManager.GetString("Label_Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surfaces.
        /// </summary>
        internal static string Label_Surfaces {
            get {
                return ResourceManager.GetString("Label_Surfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The model does not reference any stud..
        /// </summary>
        internal static string MODEL_STUDS_NOT_DEFINED {
            get {
                return ResourceManager.GetString("MODEL_STUDS_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The model does not reference any stud. Therefore the alternate model will never be displayed..
        /// </summary>
        internal static string MODEL_STUDS_NOT_DEFINED_ALT {
            get {
                return ResourceManager.GetString("MODEL_STUDS_NOT_DEFINED_ALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brick tube.
        /// </summary>
        internal static string ModelComponentType_BrickTube {
            get {
                return ResourceManager.GetString("ModelComponentType_BrickTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stud (female).
        /// </summary>
        internal static string ModelComponentType_FemaleStud {
            get {
                return ResourceManager.GetString("ModelComponentType_FemaleStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stud (male).
        /// </summary>
        internal static string ModelComponentType_MaleStud {
            get {
                return ResourceManager.GetString("ModelComponentType_MaleStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part model.
        /// </summary>
        internal static string ModelComponentType_Part {
            get {
                return ResourceManager.GetString("ModelComponentType_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} to {1}.
        /// </summary>
        internal static string NodeRangeFormat1 {
            get {
                return ResourceManager.GetString("NodeRangeFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}+.
        /// </summary>
        internal static string NodeRangeFormat2 {
            get {
                return ResourceManager.GetString("NodeRangeFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The part description is empty..
        /// </summary>
        internal static string PART_EMPTY_DESCRIPTION {
            get {
                return ResourceManager.GetString("PART_EMPTY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter a part ID..
        /// </summary>
        internal static string PART_EMPTY_PART_ID {
            get {
                return ResourceManager.GetString("PART_EMPTY_PART_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The part bounding box is not defined..
        /// </summary>
        internal static string PART_NO_BOUNDING {
            get {
                return ResourceManager.GetString("PART_NO_BOUNDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The geometry bounding box is not defined..
        /// </summary>
        internal static string PART_NO_GEOMETRYBOUNDING {
            get {
                return ResourceManager.GetString("PART_NO_GEOMETRYBOUNDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no bone defined. The part cannot be flexible..
        /// </summary>
        internal static string PROJECT_NO_BONES {
            get {
                return ResourceManager.GetString("PROJECT_NO_BONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no collision defined..
        /// </summary>
        internal static string PROJECT_NO_COLLISIONS {
            get {
                return ResourceManager.GetString("PROJECT_NO_COLLISIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no connection defined. The part will not connect with anything..
        /// </summary>
        internal static string PROJECT_NO_CONNECTIONS {
            get {
                return ResourceManager.GetString("PROJECT_NO_CONNECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No configuration problem found..
        /// </summary>
        internal static string PROJECT_NO_ISSUES {
            get {
                return ResourceManager.GetString("PROJECT_NO_ISSUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The part must have at least one surface..
        /// </summary>
        internal static string PROJECT_NO_SURFACES {
            get {
                return ResourceManager.GetString("PROJECT_NO_SURFACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The referenced stud is invalid..
        /// </summary>
        internal static string STUD_CONNECTION_FIELD_INVALID {
            get {
                return ResourceManager.GetString("STUD_CONNECTION_FIELD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The referenced stud is not defined..
        /// </summary>
        internal static string STUD_CONNECTION_FIELD_NOT_DEFINED {
            get {
                return ResourceManager.GetString("STUD_CONNECTION_FIELD_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The connection is not set or invalid..
        /// </summary>
        internal static string STUD_CONNECTION_NOT_DEFINED {
            get {
                return ResourceManager.GetString("STUD_CONNECTION_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The surface {0} does not contain any model..
        /// </summary>
        internal static string SURFACE_NO_MODELS {
            get {
                return ResourceManager.GetString("SURFACE_NO_MODELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The surface {0} has some models without texture coordinates..
        /// </summary>
        internal static string SURFACE_NO_TEXTURED_MODEL {
            get {
                return ResourceManager.GetString("SURFACE_NO_TEXTURED_MODEL", resourceCulture);
            }
        }
    }
}
