//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDDModder.BrickEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelLocalizations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDDModder.BrickEditor.Resources.ModelLocalizations", typeof(ModelLocalizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Box.
        /// </summary>
        internal static string CollisionType_Box {
            get {
                return ResourceManager.GetString("CollisionType_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sphere.
        /// </summary>
        internal static string CollisionType_Sphere {
            get {
                return ResourceManager.GetString("CollisionType_Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cylindrical (bars &amp; technic).
        /// </summary>
        internal static string ConnectorType_Axel {
            get {
                return ResourceManager.GetString("ConnectorType_Axel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ball joint &amp; misc.
        /// </summary>
        internal static string ConnectorType_Ball {
            get {
                return ResourceManager.GetString("ConnectorType_Ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs (bricks).
        /// </summary>
        internal static string ConnectorType_Custom2DField {
            get {
                return ResourceManager.GetString("ConnectorType_Custom2DField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed coupling (tires, doors &amp; etc).
        /// </summary>
        internal static string ConnectorType_Fixed {
            get {
                return ResourceManager.GetString("ConnectorType_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gear.
        /// </summary>
        internal static string ConnectorType_Gear {
            get {
                return ResourceManager.GetString("ConnectorType_Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hinge.
        /// </summary>
        internal static string ConnectorType_Hinge {
            get {
                return ResourceManager.GetString("ConnectorType_Hinge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Train rails.
        /// </summary>
        internal static string ConnectorType_Rail {
            get {
                return ResourceManager.GetString("ConnectorType_Rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slider.
        /// </summary>
        internal static string ConnectorType_Slider {
            get {
                return ResourceManager.GetString("ConnectorType_Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brick.
        /// </summary>
        internal static string Label_Brick {
            get {
                return ResourceManager.GetString("Label_Brick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tubes.
        /// </summary>
        internal static string Label_BrickTubes {
            get {
                return ResourceManager.GetString("Label_BrickTubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collisions.
        /// </summary>
        internal static string Label_Collisions {
            get {
                return ResourceManager.GetString("Label_Collisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Component.
        /// </summary>
        internal static string Label_Component {
            get {
                return ResourceManager.GetString("Label_Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connections.
        /// </summary>
        internal static string Label_Connections {
            get {
                return ResourceManager.GetString("Label_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decoration.
        /// </summary>
        internal static string Label_Decoration {
            get {
                return ResourceManager.GetString("Label_Decoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decoration surface.
        /// </summary>
        internal static string Label_DecorationSurface {
            get {
                return ResourceManager.GetString("Label_DecorationSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decoration surface {0}.
        /// </summary>
        internal static string Label_DecorationSurfaceNumber {
            get {
                return ResourceManager.GetString("Label_DecorationSurfaceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Female stud.
        /// </summary>
        internal static string Label_FemaleStud {
            get {
                return ResourceManager.GetString("Label_FemaleStud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs (female).
        /// </summary>
        internal static string Label_FemaleStuds {
            get {
                return ResourceManager.GetString("Label_FemaleStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geometry.
        /// </summary>
        internal static string Label_Geometry {
            get {
                return ResourceManager.GetString("Label_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main surface.
        /// </summary>
        internal static string Label_MainSurface {
            get {
                return ResourceManager.GetString("Label_MainSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs (male).
        /// </summary>
        internal static string Label_MaleStuds {
            get {
                return ResourceManager.GetString("Label_MaleStuds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mesh.
        /// </summary>
        internal static string Label_Mesh {
            get {
                return ResourceManager.GetString("Label_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model.
        /// </summary>
        internal static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Models.
        /// </summary>
        internal static string Label_Models {
            get {
                return ResourceManager.GetString("Label_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New part.
        /// </summary>
        internal static string Label_NewPartProject {
            get {
                return ResourceManager.GetString("Label_NewPartProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No active project.
        /// </summary>
        internal static string Label_NoActiveProject {
            get {
                return ResourceManager.GetString("Label_NoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part.
        /// </summary>
        internal static string Label_Part {
            get {
                return ResourceManager.GetString("Label_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part %partid%.
        /// </summary>
        internal static string Label_PartProjectName {
            get {
                return ResourceManager.GetString("Label_PartProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replacement mesh.
        /// </summary>
        internal static string Label_ReplacementMesh {
            get {
                return ResourceManager.GetString("Label_ReplacementMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stud.
        /// </summary>
        internal static string Label_Stud {
            get {
                return ResourceManager.GetString("Label_Stud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Studs.
        /// </summary>
        internal static string Label_Studs {
            get {
                return ResourceManager.GetString("Label_Studs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surface.
        /// </summary>
        internal static string Label_Surface {
            get {
                return ResourceManager.GetString("Label_Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surfaces.
        /// </summary>
        internal static string Label_Surfaces {
            get {
                return ResourceManager.GetString("Label_Surfaces", resourceCulture);
            }
        }
    }
}
